### GetQuestionsByExamIdCriteria
# @name GetQuestionsByExamIdCriteria
# @import ../http/users/auth.http
# @ref login
GET {{HOST}}/api/exams/10/questions?criteria= HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json


### GetQuestionByExamIdAndId
# @name GetQuestionByExamIdAndId
# @import ../http/users/auth.http
# @ref login
GET {{HOST}}/exams/10/questions/1 HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json
