GET {{HOST}}/api/exams?sectionId=1&startOn=2025-01-31T10:15:00Z HTTP/1.1
Authorization: Bearer 123
Content-Type: application/json
Accept: application/json
{

}

### GetExamsBySectionIdUserDetailIdAndCriteria
GET {{HOST}}/api/user-details/1/sections/1/exams?criteria= HTTP/1.1
Authorization: Bearer 123
Content-Type: application/json
Accept: application/json
{

}