GET {{HOST}}/api/sections HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiZXhwIjoxNzY5OTI5MDMxLCJpc3MiOiJKd3RNaW5pbWFsQXBpIiwiYXVkIjoiSnd0TWluaW1hbEFwaVVzZXJzIn0.eD3ibEdOJCd78MbE8LoJoyUcwB57dG6HcS8J5PzVDSc
Accept: application/json
{

}