### GetExamsBySectionIdStartOn
# @name GetExams
# @import ../auth/auth.http
# @ref login
GET {{HOST}}/api/exams?startOn=2025-01-31T10:15:00Z HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json
{

}

### GetExamsBySectionIdUserDetailIdAndCriteria
# @name GetExams
# @import ../auth/auth.http
# @ref login
GET {{HOST}}/api/exams?criteria= HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.token}}
Accept: application/json

### GetExamsBySectionIdUserDetailIdAndCriteriaAndStartOn
# @name GetExams
# @import ../auth/auth.http
# @ref login
GET {{HOST}}/api/exams?criteria=Qu&startOn=2025-01-31T10:15:00Z HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.token}}
Accept: application/json

### AddExam
# @name AddExam
# @import ../../http/users/auth.http
# @ref login
{{
}}
POST {{HOST}}/api/exams HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json

{
  "name": "test",
  "sectionId": 1,
  "startOn": "2026-03-01T10:15:00Z",
  "instructions": "Instruction",
  "subject": "test",
  "duration": 1
}

### Get One Exams
# @name GetExam
# @import ./users/auth.http
# @ref login
GET {{HOST}}/api/exams/100 HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json
{

}

### DeleteExam
# @name DeleteExam
# @import ./users/auth.http
# @ref login
DELETE {{HOST}}/api/exams/1?criteria= HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json
{

}

### ActivateExam
# @name ActivateExam
# @import ../../http/users/auth.http
# @ref login
PATCH {{HOST}}/api/exams/10/activate HTTP/1.1
Authorization: Bearer {{login.token}}
Content-Type: application/json
Accept: application/json
